Site/Models/Room.cs
using System.ComponentModel.DataAnnotations;
namespace Site.Models
{
    public class Room
    {
        public int Id { get; set; }
        public string? Adress { get; set; }
        public string? Landlord { get; set; }
        public decimal Price { get; set; }
        public decimal Duration { get; set; }

        public int LordId { get; set; }

        public int Rented { get; set; }
    }
}

Site/Pages/Rooms/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Site.Data;
using Site.Models;

namespace Site.Pages.Rooms
{
    public class CreateModel : PageModel
    {
        private readonly Site.Data.SiteContext _context;
        public bool fl;
        public CurrentUser nw;
        public CreateModel(Site.Data.SiteContext context)
        {
            _context = context;

        }

        public IActionResult OnGet()
        {
            fl = _context.CurrentUser.Any();
            if (fl)
            {
                nw = _context.CurrentUser.First();
            }
            return Page();
        }

        [BindProperty]
        public Room Room { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid || _context.Room == null || Room == null)
            {
                return Page();
            }
            Room.LordId = _context.CurrentUser.First().Id;
            _context.Room.Add(Room);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Site/Pages/Rooms/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Site.Data;
using Site.Models;

namespace Site.Pages.Rooms
{
    public class DeleteModel : PageModel
    {
        private readonly Site.Data.SiteContext _context;

        public DeleteModel(Site.Data.SiteContext context)
        {
            _context = context;
        }

        [BindProperty]
      public Room Room { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Room == null)
            {
                return NotFound();
            }

            var room = await _context.Room.FirstOrDefaultAsync(m => m.Id == id);

            if (room == null)
            {
                return NotFound();
            }
            else 
            {
                Room = room;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.Room == null)
            {
                return NotFound();
            }
            var room = await _context.Room.FindAsync(id);

            if (room != null)
            {
                Room = room;
                _context.Room.Remove(Room);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Site/Pages/Rooms/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Site.Data;
using Site.Models;

namespace Site.Pages.Rooms
{
    public class DetailsModel : PageModel
    {
        public readonly Site.Data.SiteContext _context;

        public bool fl;
        public CurrentUser nw;
        public DetailsModel(Site.Data.SiteContext context)
        {
            _context = context;
            fl = _context.CurrentUser.Any();
            if (fl)
            {
                nw = _context.CurrentUser.First();
            }
        }

      public Room Room { get; set; } = default!;
        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Room == null)
            {
                return NotFound();
            }

            var room = await _context.Room.FirstOrDefaultAsync(m => m.Id == id);
            if (room == null)
            {
                return NotFound();
            }
            else 
            {
                Room = room;
            }
            return Page();
        }
        public IActionResult OnPostRent(int? id)
        {
            var room = _context.Room.FirstOrDefault(m => m.Id == id);
            if (room == null)
            {
                return NotFound();
            }
            else
            {
                Room = room;
            }
            Room.Rented = 1;
            _context.Room.Update(Room);
            _context.SaveChanges();
            return RedirectToPage("Index");
        }
    }
}

Site/Pages/Rooms/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Site.Data;
using Site.Models;

namespace Site.Pages.Rooms
{
    public class EditModel : PageModel
    {
        private readonly Site.Data.SiteContext _context;

        public EditModel(Site.Data.SiteContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Room Room { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Room == null)
            {
                return NotFound();
            }

            var room =  await _context.Room.FirstOrDefaultAsync(m => m.Id == id);
            if (room == null)
            {
                return NotFound();
            }
            Room = room;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Room).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!RoomExists(Room.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool RoomExists(int id)
        {
          return (_context.Room?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Site/Pages/Rooms/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Site.Data;
using Site.Models;

namespace Site.Pages.Rooms
{
    public class IndexModel : PageModel
    {
        private readonly Site.Data.SiteContext _context;
        public bool fl;
        public CurrentUser nw;
        public IndexModel(Site.Data.SiteContext context)
        {
            _context = context;
            fl = _context.CurrentUser.Any();
            if (fl)
            {
                nw = _context.CurrentUser.First();
            }
        }

        public IList<Room> Room { get;set; } = default!;

        public async Task OnGetAsync()
        {
            if (_context.Room != null)
            {
                Room = await _context.Room.ToListAsync();
            }
        }
    }
}

Site/Pages/Rooms/Create.cshtml
@page
@model Site.Pages.Rooms.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Room</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Room.Adress" class="control-label"></label>
                <input asp-for="Room.Adress" class="form-control" />
                <span asp-validation-for="Room.Adress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Room.Landlord" class="control-label"></label>
                <input asp-for="Room.Landlord" class="form-control" value="@Model.nw.FirstName @Model.nw.LastName" readonly>
                <span asp-validation-for="Room.Landlord" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Room.Price" class="control-label"></label>
                <input asp-for="Room.Price" class="form-control" />
                <span asp-validation-for="Room.Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Room.Duration" class="control-label"></label>
                <input asp-for="Room.Duration" class="form-control" />
                <span asp-validation-for="Room.Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Site/Pages/Rooms/Delete.cshtml
@page
@model Site.Pages.Rooms.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Room</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Room.Adress)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Room.Adress)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Room.Landlord)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Room.Landlord)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Room.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Room.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Room.Duration)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Room.Duration)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Room.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

Site/Pages/Rooms/Details.cshtml
@page "{id:int?}"
@model Site.Pages.Rooms.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Room</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Room.Adress)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Room.Adress)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Room.Landlord)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Room.Landlord)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Room.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Room.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Room.Duration)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Room.Duration)
        </dd>
        <p>
            @if(Model.fl && Model.Room!=null && Model.nw.Role==1)
            {
                @if (Model.Room.Rented == 0)
                {
                    <form method="post">
                        <button asp-page-handler="Rent">Арендовать</button>
                </form>
                }
            }
        </p>
    </dl>
</div>
<div>
    <a asp-page="./Index">Back to List</a>
</div>

Site/Pages/Rooms/Edit.cshtml
@page
@model Site.Pages.Rooms.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Room</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Room.Id" />
            <div class="form-group">
                <label asp-for="Room.Adress" class="control-label"></label>
                <input asp-for="Room.Adress" class="form-control" />
                <span asp-validation-for="Room.Adress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Room.Landlord" class="control-label"></label>
                <input asp-for="Room.Landlord" class="form-control" readonly />
            </div>
            <div class="form-group">
                <label asp-for="Room.Price" class="control-label"></label>
                <input asp-for="Room.Price" class="form-control" />
                <span asp-validation-for="Room.Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Room.Duration" class="control-label"></label>
                <input asp-for="Room.Duration" class="form-control" />
                <span asp-validation-for="Room.Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Site/Pages/Rooms/Index.cshtml
@page
@model Site.Pages.Rooms.IndexModel

@{
    ViewData["Title"] = "Rooms";
}
<h1>Rooms</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Room[0].Adress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Room[0].Landlord)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Room[0].Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Room[0].Duration)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Room) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Adress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Landlord)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Duration)
            </td>
            <td>

					<a asp-page="./Details" asp-route-id="@item.Id">Details</a>
                    @if (Model.fl) {
                        @if (Model.nw.Id == item.LordId)
                        {
                            <a>|</a>

                            <a asp-page="./Edit" asp-route-id="@item.Id">Edit</a>

                            <a>|</a>
                            <a asp-page = "./Delete" asp-route-id = "@item.Id" > Delete </a >
                        }
                    }
            </td>
        </tr>
}
    </tbody>
</table>

Site/Pages/Rooms/Login.cshtml
@page
@model Site.Pages.LoginModel
@{
}
@if(!Model.fl){
<form  class="As" method="post">
    <span asp-validation-for="Input.Email" class="text-danger"></span>
    <input asp-for="Input.Email" placeholder="Почта" type="text" required>
    <br>
    <span asp-validation-for="Input.Password" class="text-danger"></span>
    <input asp-for="Input.Password" placeholder="Пароль" type="password" required>
    <br>
    <button type="submit" >Войти</button>
    <br>
    <a class="nav-link text-dark" asp-page="Registration">Регистрация</a>
    <a class="nav-link text-dark" asp-page="Index">Вернуться</a>
</form>
}
else{

    <p><a>@Model.nw.FirstName</a>

    <a>@Model.nw.LastName</a></p>

    <p><a>@Model.nw.Phone</a></p>

    <p><a>@Model.nw.Email</a></p>
    @if (Model.nw.Role ==2)
    {

        <p>
            <a asp-page="Create">Create New</a>
        </p>
    }
    else
    {
        
    }
    <form method="post">
        <button asp-page-handler="Exit">Exit</button>
    </form>
}

Site/Pages/Rooms/Registration.cshtml
@page
@model Site.Pages.RegistrationModel
@{
}
<form class="As" method="post">
    <div>
        <input placeholder="Имя" asp-for="Input.FirstName" required />
    </div>
    <div>
        <input placeholder="Фамилия" asp-for="Input.LastName" required />
    </div>
    <div>
        <span asp-validation-for="Input.Phone" class="text-danger"></span>
        <input placeholder="Телефон в формате +7-***-***-**-**" style="width:267px" type="tel" asp-for="Input.Phone" required />
    </div>
    <div>
        <span asp-validation-for="Input.Email" class="text-danger"></span>
        <input placeholder="Почта" type="email" asp-for="Input.Email" required />
    </div>
    <div>
        <input placeholder="Пароль" type="password" asp-for="Input.Password" required />
    </div>
    <div>
        <span asp-validation-for="Input.ConfirmPassword" class="text-danger"></span>
        <input placeholder="Подтвердите пароль" type="password" asp-for="Input.ConfirmPassword" required />
    </div>
    <div>
        <input type="radio" asp-for="Input.Role" value="tenant" required /> Аренатор
        <input type="radio" asp-for="Input.Role" value="landlord" required /> Арендодатель
    </div>
    <br>
    <input type="submit" value="Register" /><br>

    <a class="nav-link text-dark" asp-page="Login">Вход</a>
    <a class="nav-link text-dark" asp-page="Index">Вернуться</a>
</form>